#!bin/bash

if [[ -z "$PYFILE"]]; then
	echo "Error: Environment variable not set"
	exit 1
fi

if [[! -f "$PYFILE"]]; then
	echo "Error: File assosciated with $PYFILE does not exist"
	exit 1
fi

python $PYFILE
